add support for ipv4 peers
zig-bitcoin/btczee pull request #121
Opened 2024-09-24 16:20 UTC by Jonatan-Chaverri

Closes https://github.com/zig-bitcoin/btczee/issues/119

2024-09-24 20:08 UTC, tdelabro approved these changes

2024-09-24 20:08 UTC, tdelabro requested changes

2024-09-24 20:08 UTC, tdelabro commented on src/network/peer.zig
> +            return error.UnsupportedAddressFamily;
Can you remove the "WeOnlySupportIPV6ForNow" error?
the whole `PeerError`

2024-09-24 20:09 UTC, tdelabro requested changes

2024-09-24 20:09 UTC, tdelabro commented on src/network/peer.zig
> +        var stream: std.net.Stream = undefined;
roll back to initializing the stream when you create it `const stream =`

2024-09-24 20:10 UTC, tdelabro requested changes

2024-09-24 20:10 UTC, tdelabro commented on src/network/peer.zig
> +        stream = try std.net.tcpConnectToAddress(final_address);
We can keep using the original address there.

We need the conversion for when we are doing the sendVersionMessage thing

2024-09-30 20:37 UTC, tdelabro requested changes

2024-09-30 20:37 UTC, tdelabro commented on src/network/peer.zig
> +        }
this will be needed for other messages.
Move it as a standalone method under message/utils.zig

2024-09-30 20:37 UTC, tdelabro commented on src/network/peer.zig
> +            ipv6_mapped[15] = ipv4_bytes[3];
`@memcpy(&ipv6_mapped[12..16], ipv4_bytes[4])`

2024-09-30 20:37 UTC, tdelabro commented on src/network/peer.zig
> +            };
https://ziglang.org/documentation/master/std/#std.net.Address.initIp6

2024-09-30 22:01 UTC, Jonatan-Chaverri commented on src/network/peer.zig
> +                        .scope_id = 0,
FlowInfo is used for Quality of Service in v6 and scope_id to specify the interface index when you have multiple network cards. Both are concepts associated with ipv6 and has no particular mapping from ipv4. So I just used the default for both. 0 in flowinfo means no special flow and in scope id means no specific scope. Both are safe options when doing the parsing.

2024-10-01 11:27 UTC, tdelabro requested changes

2024-10-01 11:27 UTC, tdelabro commented on src/network/peer.zig
> +        }
You don't update self, you just convert to ipv6 when you build the message.

```zig
const address = if (self.address.any.family == std.posix.AF.INET) MessageUtils.convertIPv4ToIPv6(self.address) else self.address;

const message = protocol.messages.VersionMessage.new(
  ...,
  { .ip = address.in6.sa.addr, .port = address.getPort(), .services = 0 },
  ```

2024-10-01 11:27 UTC, tdelabro commented on src/network/peer.zig
>      fn sendVersionMessage(self: *Peer) !void {
self: *const Peer

2024-10-02 09:08 UTC, tdelabro approved these changes

2024-10-02 09:08 UTC, merged