Adding filter clear message
zig-bitcoin/btczee pull request #129
Opened 2024-09-25 22:54 UTC by Gerson2102

Solves #94

2024-09-26 08:20 UTC, tdelabro approved these changes

2024-09-26 08:20 UTC, tdelabro commented on src/network/protocol/messages/filterclear.zig
> +
empty lane

2024-09-26 08:20 UTC, tdelabro commented on src/network/protocol/messages/filterclear.zig
> +const native_endian = @import("builtin").target.cpu.arch.endian();
you are not using this import

2024-09-26 12:42 UTC, tdelabro commented
@Gerson2102 few fixes and resolve conflicts

2024-09-26 16:01 UTC, Gerson2102 commented
I think we are good now sir. Let me know @tdelabro

2024-09-27 08:52 UTC, tdelabro requested changes

2024-09-27 08:52 UTC, tdelabro commented on src/network/protocol/messages/filterclear.zig
> +        return protocol.CommandNames.FILTERCLEAR ++ [_]u8{0} ** 5;
`FILTERCLEAR` is already 11 char + final `\0`. No need to append anything to it in order to reach `*const [12]u8`

2024-09-27 15:23 UTC, tdelabro approved these changes

2024-09-27 15:27 UTC, merged