Feat/addr
zig-bitcoin/btczee pull request #135
Opened 2024-09-27 04:22 UTC by oxlime

should resolve #75

2024-09-27 09:28 UTC, tdelabro requested changes
Good job!

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +const native_endian = @import("builtin").target.cpu.arch.endian();
not used

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +const Endian = std.builtin.Endian;
not used

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +/// https://developer.bitcoin.org/reference/p2p_networking.html#addr
this doc goes on the AddrMessage struct

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +        try w.writeAll(std.mem.asBytes(&ip_address.ip));
indentation

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +        return 1 +  self.ip_addresses.len * fixed_length_per_ip;// 1 for CompactSizeUint
CompactSizeUint len is not 1, it's CompactSizeUint.new(ip_addresses.len).hint_encoded_size()

The bigger the number, the more bytes it takes to write it

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +    return true;
indentation

2024-09-27 09:28 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +    return true;
run `zig fmt`

2024-09-27 09:28 UTC, tdelabro commented on src/network/wire/lib.zig
> +
not used, or only inside your test, if so move them there

2024-09-27 09:28 UTC, tdelabro commented on src/network/wire/lib.zig
> +    //const ServiceFlags = protocol.ServiceFlags;
remove

2024-09-27 09:28 UTC, tdelabro commented on src/network/wire/lib.zig
> +//    }
forgot to remove this

2024-09-30 10:36 UTC, tdelabro requested changes

2024-09-30 10:36 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +        }
create a NetworkIpAddress.deserializeReader method

2024-09-30 10:36 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +        }
same

2024-09-30 10:36 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +        //try CompactSizeUint.new(@intCast(self.ip_addresses.len)).encodeToWriter(w);
forgotten comment

2024-10-02 09:38 UTC, tdelabro commented
@oxlime are you still working on this?

2024-10-02 15:54 UTC, tdelabro requested changes

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +    pub fn serializeWriter(self: *const NetworkIPAddr, writer: anytype) !void {
serializeToWriter

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +pub const NetworkIPAddr = struct {
part of it already exists under src/network/protocol/NetworkAddress.zig

please use it

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +pub const NetworkIPAddr = struct {
You can reorder the fields if you want

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +pub const NetworkIPAddr = struct {
so you have a struct which is time + NetworkAddress

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +        Sha256.hash(&digest, &digest, .{});
use generic checksum

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +            if (!std.meta.hasFn(@TypeOf(w), "writeAll")) @compileError("Expects r to have fn 'writeAll'.");
you are using none of those. so don't check

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/addr.zig
> +            if (!std.meta.hasFn(@TypeOf(r), "readAll")) @compileError("Expects r to have fn 'readAll'.");
same

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/lib.zig
> +            .addr => |m| m.checksum(),
|*m|

2024-10-02 15:54 UTC, tdelabro commented on src/network/protocol/messages/lib.zig
> +            .addr => |m| m.hintSerializedLen(),
|*m|

2024-10-03 09:17 UTC, tdelabro approved these changes

2024-10-03 09:18 UTC, tdelabro commented
@oxlime just rebase and I will merge

2024-10-04 09:28 UTC, tdelabro commented
@oxlime sorry you need to fix conflicts again :,(

2024-10-04 15:52 UTC, ybensacq commented on src/network/protocol/messages/addr.zig
> +    pub fn serialize(self: *const AddrMessage, allocator: std.mem.Allocator) ![]u8 {
you can use the generic function

2024-10-04 15:53 UTC, ybensacq commented on src/network/protocol/messages/addr.zig
> +    pub fn deserializeSlice(allocator: std.mem.Allocator, bytes: []const u8) !AddrMessage {
we have a generic function for this one as well.

2024-10-07 11:43 UTC, tdelabro approved these changes

2024-10-07 11:43 UTC, merged