feat/blocktxn
zig-bitcoin/btczee pull request #154
Opened 2024-10-02 21:59 UTC by guha-rahul

addresses #102

2024-10-03 08:58 UTC, tdelabro requested changes

2024-10-03 08:58 UTC, tdelabro commented on src/network/protocol/messages/blocktxn.zig
> +/// BlockTxnMessage represents the "BlockTxn" message
add empty line

2024-10-03 08:58 UTC, tdelabro commented on src/network/protocol/messages/blocktxn.zig
> +        // 32 bytes for the block header
the block hash, not the header

2024-10-03 08:58 UTC, tdelabro commented on src/network/wire/lib.zig
> +// Return the checksum of a slice
add empty line

2024-10-03 08:58 UTC, tdelabro commented on src/network/wire/lib.zig
> +const CompactSizeUint = @import("bitcoin-primitives").types.CompatSizeUint;
Move the Error bellow the imports

2024-10-03 15:30 UTC, bloomingpeach commented
this code is for `GetBlockTxn` not `BlockTxn`

2024-10-03 15:31 UTC, bloomingpeach commented
`BlockTxn` payload has `Transaction` field, not `indexes`
![image](https://github.com/user-attachments/assets/dbdc3cc1-fd1c-481f-8a49-46796310a7b8)

2024-10-04 08:28 UTC, tdelabro commented
@guha-rahul, @bloomingpeach is right, you confused both payload

2024-10-04 08:29 UTC, tdelabro requested changes

2024-10-04 10:18 UTC, ybensacq commented on src/network/protocol/messages/blocktxn.zig
> +    pub fn deserializeSlice(allocator: std.mem.Allocator, bytes: []const u8) !Self {
now we have a `genericDeserializeSlice`

2024-10-04 10:19 UTC, ybensacq commented on src/network/protocol/messages/blocktxn.zig
> +    pub fn serialize(self: *const Self, allocator: std.mem.Allocator) ![]u8 {
we have `genericSerialize` you can call it in this function

2024-10-07 05:37 UTC, ybensacq commented on src/network/protocol/messages/lib.zig
> +            .filterload => {},
it can be removed, because managed in the else.

2024-10-07 05:38 UTC, ybensacq commented on src/network/protocol/messages/blocktxn.zig
> +    const deserialized = try BlockTxnMessage.genericDeserializeSlice(test_allocator, serialized);
you have to use deserialize from BlockTxnMessage not the generic one

2024-10-07 12:02 UTC, tdelabro commented
@guha-rahul I'm closing this PR as the project is put in hold. I will still pay you for the work done on OD tho.

2024-10-07 12:02 UTC, closed without merging